services:
  chatroom:
    build: .
    ports:
      - 8888:8888
    working_dir: /chatroom
    volumes:
      - .:/chatroom
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: chatroom
      MLOG_SWITCH: "TRUE"
      MLOG_TERMINAL_SWITCH: "TRUE"
      MLOG_TERMINAL_LEVEL: IWEF
      MLOG_FILE_SWITCH: "FALSE"
      MLOG_FILE_LEVEL: IWEF
      MLOG_FILE_NAME: test_log
      MLOG_FILE_PATH: /home/mars/code/cpp_log/
      MLOG_DETAILS: "TRUE"
      MLOG_TIME: "TRUE"
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
    command: /bin/bash -c "while true; do sleep 1000; done"

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatroom

  redis:
    image: redis:7.0
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
